[project]
name = "sip009-nft"
authors = []
description = ""
telemetry = false
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"


[contracts.my-lovely-nft]
path = "contracts/my-lovely-nft.clar"

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
